#!/bin/bash -eu

docker build -f Dockerfile.1 -t micro-debian .
docker create --name micro-debian micro-debian
docker export micro-debian >micro-debian.tar
docker rm micro-debian
docker rmi micro-debian
docker build -f Dockerfile.2 -t accursoft/micro-debian .
rm micro-debian.tar