FROM debian:stretch

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Yes, do as I say!" | apt-get purge \
    startpar \
    tzdata \
    bash \
    iproute2 \
    e2fslibs \
    libgpg-error0 \
    ncurses-bin \
    libncurses5 \
    libncursesw5 \
    ncurses-base \
    inetutils-ping \
    libsmartcols1 \
    insserv \
    libkmod2 \
    libcomerr2 \
    libcap2-bin \
    libudev1 \
    libuuid1
# bash removed, update passwd
RUN sed -i 's/bash/sh/g' /etc/passwd

WORKDIR /usr/share
# preserve copyright files
RUN tar -czf copyrights.tar.gz common-licenses doc/*/copyright
RUN sed 's|doc/\*/copyright|copyrights.tar.gz|' /etc/motd
# clean up
COPY post-apt dev /opt/
RUN /opt/post-apt
RUN rm -r \
    common-licenses \
    ~/.bashrc \
    /usr/lib/locale/C.UTF-8 \
    /lib/lsb \
    /lib/udev