#!/bin/sh -eu

apt-get autoremove --purge -y
apt-get clean
cd /usr/share
# preserve copyrights
if stat -t doc/*/copyright >/dev/null 2>&1; then
  gunzip copyrights.tar.gz
  tar -rf copyrights.tar doc/*/copyright
  gzip copyrights.tar
fi
# clean up
rm -rf \
  /var/lib/apt/lists/* \
  doc \
  man \
  info \
  locale \
  /var/log/* \
  /var/cache/debconf/*