#!/bin/sh -eu

docker pull debian:stretch
./build
docker run --rm -e DEBIAN_FRONTEND=noninteractive accursoft/micro-debian sh -c "apt-get update && apt-get install -y curl && curl https://google.com >/dev/null"