FROM accursoft/micro-jessie

RUN apt-get update
RUN apt-get install -y --no-install-recommends cdebconf
ENV DEBCONF_USE_CDEBCONF yes
# dummy package so we can remove perl/debconf without breaking dependencies
COPY debconf_2_all.deb /
# we need to keep confmodule
WORKDIR /usr/share
RUN cp debconf/confmodule /tmp
# install dummy package, removes real debconf
RUN dpkg -i /debconf_2_all.deb
# redirect debconf scripts to cdebconf
RUN echo "exec /usr/lib/cdebconf/dpkg-preconfigure $0 \"$@"\" >/usr/sbin/dpkg-preconfigure
RUN chmod a+x /usr/sbin/dpkg-preconfigure
RUN mkdir debconf && mv /tmp/confmodule debconf
# now we can remove perl
RUN echo "Yes, do as I say!" | apt-get purge perl-base
COPY perl /usr/bin/
# clean up
RUN /opt/post-apt
RUN rm /debconf_2_all.deb